#!/bin/bash
echo "Please enter the name of the Cricket Team that u want to know about their performance in the World Cup Tournament:"
read team
if [ $team == WestIndies ];
 then
  echo "Two times WestIndies won the World Cup"
  echo "Years:1975 & 1979"

elif [ $team == India ];
 then
  echo "Two times India won the World Cup"
  echo "Years:1983 & 2011"

elif [ $team == Australia ];
 then
  echo "Five times Australia won the World Cup"
  echo "Years:1987 & 1999 & 2003 & 2007 & 2015"

elif [ $team == Pakistan ];
 then
  echo "Only one time Pakistan has managed to win a World Cup"
  echo "Year:1992"

elif [ $team == SriLanka ];
 then
  echo "Only one time SriLanka has managed to win a World Cup"
  echo "Year:1996"

elif [ $team == SouthAfrica ];
 then
  echo "Firstly they had to reach the final in order to win a World Cup"

elif [ $team == NewZealand ];
 then
  echo "They managed to entered into the finals of ICC CRICKET WORLD CUP 2015 but failed to win the World Cup as they los t to Australia"

elif [ $team == Bangaldesh ];
 then
  echo "They managed to qualify for the quarter-finals for the 1st time in the World Cup 2015 but failed to win against India"

else

    echo "The teams are not yet qualified for the quarter-finals stage"

fi


