FROM centos
MAINTAINER madhavdocker453 <madhavguvvuala@gmail.com>
RUN yum update -y && yum install wget -y
RUN yum install unzip git -y
RUN touch /opt/madhav \
&& echo 'hai Dockerfile' >> /opt/madhav
RUN wget <application-url>
