FROM centos
MAINTAINER madhavdocker453 <madhavguvvuala@gmail.com>
RUN yum install wget -y\
&& yum install unzip -y && yum install git -y \
&& cd /opt && wget http://mithuntechnologies.com/jdk-8u211-linux-x64.rpm && yum install jdk-8u211-linux-x64.rpm -y \
&& wget http://apachemirror.wuchna.com/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip \
&& unzip apache-maven-3.6.1-bin.zip \
&& rm -rf *.zip
ENV JAVA_HOME=/usr/java/jdk1.8.0_211-amd64/jre
ENV PATH=$PATH:$JAVA_HOME/bin
ENV M2_HOME=/opt/apache-maven-3.6.1
ENV PATH=$PATH:$M2_HOME/bin
  # We can also use ENV keyword like this eg: ENV Ant BuildTool {usuage: echo $ANT} {Result: BuildTool} 
